# Generated by Django 5.1.6 on 2025-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_uploadedfile_file_url_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
