# Generated by Django 5.1.6 on 2025-05-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_uploadedfile_file_uploadedfile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_data'),
        ),
    ]
