# Generated by Django 5.1.6 on 2025-05-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='accounts.user_data', to_field='email'),
        ),
    ]
