# Generated by Django 5.1.6 on 2025-05-10 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_uploadedfile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='accounts.user_data', to_field='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
