# Generated by Django 5.1.6 on 2025-05-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_uploadedfile_user_alter_uploadedfile_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
