# Generated by Django 4.2.7 on 2025-06-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_notification_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient_email',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user_data'),
            preserve_default=False,
        ),
    ]
